### ISSUE TITLE
New translations

### ISSUE THREAD

**Issue by sekl** [loomnetwork/dc-translations#9]
- profile.notifications: 'Notifications'
- job_board.search_placeholder: "Search jobs"
- job_board.search: "Search"
- job_board.heading.edit: 'Editing Job'
- job_board.heading.new_job: 'New Job'
- show: 'Show'

```
helpers:
    label:
      job:
        title: 'Title:'
        description: 'Description:'
        tag_list: 'Tags (separated by commas)'
    submit:
      job:
        create: "Create Job"
        update: "Update Job"
```
